### ISSUE TITLE
Pretty much all trash in Spider Wing can be CC'ed somehow

### ISSUE THREAD

**Issue by Braindot** [elysium-project/naxxramas_ptr_feedback#16]
I think the GM's watching already stated they didnt have any checks in place for CC immunities, but I dont see a bugreport for it yet so here it is.

Every single trash mob was able to be CC'ed in one way or the other.

**Comment by sneakdella** [comment]
Spiders can be sheeped, I can confirm this.

- Spudicus

**Comment by blubba22** [comment]
Yeah, stunning, sleeping, even taming were all possible for us as well.

**Comment by kevmodrome** [comment]
Plagued Ghouls are apparently supposed to be tauntable:

"Strategies: 
*Tank them away from the group and kill them last. They are stunnable, so stunning is a good option to reduce damage and cleaves."

Same with Shade of Naxxramas:

"Also found in the spider wing. They can be stunned so that's basically the deal. Nuke em down otherwise they start summoning spirits (like in ZG). Don't stand near spirits or they'll wreck you."

Source:
- http://z13.invisionfree.com/Tofu/ar/t1963.htm

**Comment by kevmodrome** [comment]
The Acolyte and Cultist groups should most likely not be CC:able. Not mentioned in the strategies.

Regarding Acolytes:
"AE if too many players in range. (does not list the amount of people allowed)

Strategies On:
all melee on the Acolytes, however limit perhaps 4 people to each acolyte (their aoe is triggered if too many people are near them, im assuming 4 like skeram) "

and
Cultists:
"Strategies:
one possibility is having ranged dps / casters huddled in one area of the room. NO MELEE ON THESE GUYS (AoE 500 dmg shadow auras) they must be tanked far away from the Acolytes"


Source:
- http://z13.invisionfree.com/Tofu/ar/t1963.htm

**Comment by Pleasant-Elysium** [comment]
Might be helpful if we can find what CC's should be able to be used: i.e. interrupts on Cultist groups? Sheeps / Sleep ever?

**Comment by gemt** [comment]
All spider trash and trash around Faerlina has had a bunch of immune flags added. More feedback is welcomed after next test session.
