### ISSUE TITLE
Boss-leashing

### ISSUE THREAD

**Issue by gemt** [elysium-project/naxxramas_ptr_feedback#33]
Currently no bosses will leash at any point. They follow you anywhere in the instance until everyone it's in combat with are dead.

Without currently having any sources, it may be the case that certain bosses, if not all, should leash when if they move out of their "room". Sources on this is needed.

**Comment by kevmodrome** [comment]
You used to be able to kite Patchwerk in Spiderwing after the first door. To stop people from killing him this way added an ability to his Berserk phase: "Patchwerk will AOE shoot Slime Bolts to the whole the raid for ~25000 nature damage. (Most likely the fix for kiting exploit"

Many of the other bosses had doors that made it impossible to kite them, examples are Loatheb, Gothik, Heigan, Thaddius, etc. I will look for sources later.

Source:
Patchwerk being kited: https://www.youtube.com/watch?v=GTAJtJglKEA

**Comment by gemt** [comment]
I'm aware of the pw thing. Doors will, as you say, prevent people from running out of areas to reset, but as bosses put themself in combat with the zone, someone could potentially be afk at the entrance when a boss is pulled and be put in combat by the boss if someone else pulls it. In that case, the boss will run all the way to the entrance if the raid wipes.

Whether or not the boss should leach at some point then is the question.
