### ISSUE TITLE
Spirit of Zanza and Spirit of Zandalar

### ISSUE THREAD

**Issue by Crematorya** [elysium-project/naxxramas_ptr_feedback#47]
Spirit of Zanza (http://db.vanillagaming.org/?item=20079) should cost 1 Zandalar Honor Token (http://db.vanillagaming.org/?item=19858) and must fall off at death.
Spirit of Zandalar (http://db.vanillagaming.org/?spell=24425) must fall off at death.

> - World of Warcraft Client Patch 1.11.0 (2006-06-20)
> - The Spirit of Zandalar will no longer persist through death.

**Comment by Kamisayo** [comment]
Just chiming in to add a few additional sources, since the 1.11 patch notes themselves only mention Spirit of Zandalar (the buff given when Heart of Hakkar is turned in), and not the three types of Zanza potions (purchased with honor tokens).

Patch 1.11 did indeed change those potions to no longer last through death and reduced their cost to 1 token:
http://www.shadowsongeurope.com/forum/archive/index.php/t-11850.html
http://www.lurkerlounge.com/forums/printthread.php?tid=4203&page=3
http://blue.cardplace.com/cache/wow-general/8731767.htm

**Comment by gemt** [comment]
Fixed, the 1 token cost part will hit live soon
