### ISSUE TITLE
Naxxramas and Reputation

### ISSUE THREAD

**Issue by gemt** [elysium-project/naxxramas_ptr_feedback#53]
Pretty much nothing gives reputation in Naxxramas atm. To my knowledge most should give Argent Dawn reputation, but how much and who should not requires some research.

If anyone have any information on this topic, please share.

**Comment by kevmodrome** [comment]
I don't know which level of reputation these people have but at least it's something.

Anub'Rekhan: 100 (https://youtu.be/wS_CJyMVfA0?t=2m56s)
Faerlina: 100 (https://youtu.be/czibvG1pOGI?t=3m41s)
Maexxna: 100 (https://youtu.be/va8nE2U0YSY?t=4m10s)

Patchwerk: 100 (https://www.youtube.com/watch?v=p_fT7Vy_tow&t=105s)
Grobbulus: 100 (https://youtu.be/E1zZrldAz0A?t=5m42s)
Gluth: 100 (https://youtu.be/cPsllhvKJZw?t=7m52s)
Thaddius: 100 (https://youtu.be/TJsCv2lU3u8?t=8m38s)

Noth: - (Not sure, most likely 100?)
Heigan: 100 (https://youtu.be/wcHcHTAGGso?t=6m57s)
Loatheb: 100 (https://youtu.be/_hC1NYeBv18?t=6m12s bottom right, 110 because Human)

Razuvious: 100 (https://youtu.be/7WIDKJo0vdw?t=5m34s)
Gothik: - - (Not sure, most likely 100?)
4HM: Most videos I can find show no rep gain. Already exalted? Most likely 100?

Sapphiron: Most videos I can find show no rep gain. Already exalted?
Kel'Thuzad: Most videos I can find show no rep gain. Already exalted?

Trash, I have no idea about.

**Comment by ettern** [comment]
Noth: 100 (https://youtu.be/I-GYu1_rwEc?t=9m13s)
Gothik: 100 (https://youtu.be/7E8cjgeFU1Y?t=2m47s)

**Trash**
_Spider Wing_
Poisonous Skitterer: 0
Cenarion Spinner: 0
Dread Creeper: 0
Venom Stalker: 0

**Comment by ettern** [comment]
_Abomination Wing_
Patchwork Golem: 25 (https://wow.gamepedia.com/index.php?title=Patchwork_Golem&oldid=298520)
Bile Retcher: Unknown (No reputation report for these on gamepedia/wowwiki - https://wow.gamepedia.com/index.php?title=Bile_Retcher&oldid=373251)
Sludge Belcher: Unknown (No reputation report for these on gamepedia/wowwiki - https://wow.gamepedia.com/index.php?title=Sludge_Belcher&oldid=314732)
Embalming Slime: 0 (https://wow.gamepedia.com/index.php?title=Embalming_Slime&oldid=181646) Makes sense since these mobs respawn every minutes (Grobbulus throws them down)
Sewage Slime: Unknow (https://wow.gamepedia.com/index.php?title=Sludge_Belcher&oldid=314732) Most likely 0 because they respawn every 3 minutes.
Living Monstrosity: 25 until revered, probably same for every mob that yields reputation (https://wow.gamepedia.com/index.php?title=Living_Monstrosity&oldid=337500)
Mad Scientist: Unknown (https://wow.gamepedia.com/index.php?title=Mad_Scientist&oldid=237034)
Surgical Assistant: Unknown (https://wow.gamepedia.com/index.php?title=Surgical_Assistant&oldid=326954)
Stitched Spewer: Unknown (https://wow.gamepedia.com/index.php?title=Stitched_Spewer&oldid=338315)

**Comment by ettern** [comment]
_Plague Wing_
Plague Slime: 0 (Havent found a single trash farm video where these yield reputation - https://wow.gamepedia.com/index.php?title=Plague_Slime&oldid=383694)
Infectious Ghoul: 0 (Havent found a single trash farm video where these yield reputation - https://wow.gamepedia.com/index.php?title=Infectious_Ghoul&oldid=383695)
Stoneskin Gargoyle: 25 (https://wow.gamepedia.com/index.php?title=Stoneskin_Gargoyle&oldid=170035)Worth to mention that you get 25 reputation when you are revered.

**Comment by ettern** [comment]
_Death Knight Wing_
Risen Deathknight: 0 (https://wow.gamepedia.com/index.php?title=Risen_Deathknight&oldid=171933)
Death Knight: Unknown (https://wow.gamepedia.com/index.php?title=Death_Knight_(mob)&oldid=337448)
Death Knight Captain: 0 (https://wow.gamepedia.com/index.php?title=Death_Knight_Captain&oldid=190553)
Shade of Naxxramas: Unknown (https://wow.gamepedia.com/index.php?title=Shade_of_Naxxramas&oldid=253394)
Necro Knight: Unknown (https://wow.gamepedia.com/index.php?title=Necro_Knight&oldid=306687)
Doom Touched Warrior: Unknown (https://wow.gamepedia.com/index.php?title=Doom_Touched_Warrior&oldid=195246)
Dark Touched Warrior: Unknown (https://wow.gamepedia.com/index.php?title=Dark_Touched_Warrior&oldid=337442)
Skeletal Smith: Unknown (https://wow.gamepedia.com/index.php?title=Skeletal_Smith&oldid=355116)
Bony Construct: Unknown (https://wow.gamepedia.com/index.php?title=Bony_Construct&oldid=355117)
Death Knight Cavalier: 50 (https://wow.gamepedia.com/index.php?title=Death_Knight_Cavalier&oldid=337450)
Death Lord: 50 (https://wow.gamepedia.com/index.php?title=Death_Lord&oldid=337445)
Skeletal Steed: 0 (https://wow.gamepedia.com/index.php?title=Skeletal_Steed&oldid=338332) - ON PTR these are named "Deathcharger Steed" which is incorrect. See [#91](https://github.com/elysium-project/naxxramas_ptr_feedback/issues/91)
Unholy weapons: Unknow

**Comment by gemt** [comment]
A reputation system has been added. If anyone find anything to be wrong please report.
